version: '3.1'

services:
  redis:
    image: 'redis:alpine'
    command: redis-server
    expose:
      - '6379'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
  postgres:
    image: postgres
    container_name: 'notes-postgres'
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: notes
    ports:
      - '5432:5432'
  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - '80:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'manjo@manjo.com'
      PGADMIN_DEFAULT_PASSWORD: 'manjaca'
    depends_on:
      - postgres
volumes:
  redis-data:
  redis-conf:
